CREATE DATABASE treedb;

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE inventory.callready(
   CALL_ID SERIAL PRIMARY KEY NOT NULL,
   CUSTOMER_NAME VARCHAR(255) NOT NULL,
   SHIPPING_ADDRESS VARCHAR(255),
   PHONE VARCHAR(255),
   EMAIL VARCHAR(255),
   CUSTOMER_REP VARCHAR(255),
   CUSTOMER_PO VARCHAR(255),
   GLC_BOL VARCHAR(255),
   GLC_BOL2 VARCHAR(255),
);

CREATE TABLE inventory.pieces(
   ROW INT NOT NULL,
   CALL_ID INT NOT NULL,
   THICKNESS NUMERIC,
   WIDTH NUMERIC,
   LENGTH NUMERIC,
   PRIMARY KEY(contact_id),
   CONSTRAINT fk_customer
      FOREIGN KEY(CALL_ID) 
         REFERENCES callready(CALL_ID)
);