version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: ts-backend
    environment:
      APP_ENV: dev
    ports:
    - "5000:5000"

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: ts-backend
    expose:
    - "5000"

  nginx:
    image: nginx:1.21
    volumes:
      - "./nginx/config/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "5000:80"
    expose:
      - "80"
    depends_on:
      - backend
    links:
      - backend